"""
Golden file test vectors for KidneyHood prediction engine.

Source: finalized-formulas.md Section 7 — calc spec v1.0 golden file.
These are the canonical expected values from the calculation specification.

IMPORTANT: These vectors were generated by the SPEC's simplified model
(0.31 coefficient, fixed tier targets, no age adjustment, Phase 1 completes
at month 3, Phase 2 spans months 6-24). The current engine (engine.py)
implements Phase 1 completing at month 3 with Phase 2 starting at month 3,
using the phase1_cap mechanism from TIER_CONFIG. This produces outputs that
diverge from these vectors — often by 1-5 eGFR points beyond the ±0.2 tolerance.

Open question Q1 (finalized-formulas.md Section 8): Lee must confirm which
formula set the golden vectors are based on before the ±0.2 gate can be applied
to the treatment trajectories. Until Lee responds, golden file tests for
treatment paths should be marked xfail with the Q1 reference.

The no-treatment golden values are much closer to the engine output (within ±0.5)
and the main discrepancy there (growing from t=24 onward) appears to be a BUN
modifier difference: the engine adds a BUN modifier of (35-20)/10*0.15 = 0.225
mL/min/yr to the decline rate, producing -2.425/yr vs spec's apparent -2.2/yr.

DIALYSIS_THRESHOLD: 12.0 (not 15 — confirmed engine.py constant).
TOLERANCE: ±0.2 eGFR per calc spec Section 4.
"""

# ---------------------------------------------------------------------------
# Time points (must match engine.TIME_POINTS_MONTHS exactly)
# ---------------------------------------------------------------------------

TIME_POINTS_MONTHS = [0, 1, 3, 6, 12, 18, 24, 36, 48, 60, 72, 84, 96, 108, 120]

# ---------------------------------------------------------------------------
# Vector 1 — Spec Example (BUN 35, eGFR 33, Age 58)
# Source: finalized-formulas.md Section 7, calc spec Section 4
# ---------------------------------------------------------------------------

GOLDEN_VECTOR_1_INPUT = {
    "bun": 35,
    "creatinine": 2.1,
    "age": 58,
    "egfr_override": 33.0,
}

# Spec expected values keyed as (time_month, path)
# Path keys match engine.predict() trajectories dict:
#   "no_treatment", "bun_18_24", "bun_13_17", "bun_12"
GOLDEN_VECTOR_1_EXPECTED = {
    (0, "no_treatment"): 33.0,   (0, "bun_18_24"): 33.0,
    (0, "bun_13_17"): 33.0,      (0, "bun_12"): 33.0,
    (1, "no_treatment"): 32.8,   (1, "bun_18_24"): 34.0,
    (1, "bun_13_17"): 34.6,      (1, "bun_12"): 35.4,
    (3, "no_treatment"): 32.3,   (3, "bun_18_24"): 35.7,
    (3, "bun_13_17"): 36.9,      (3, "bun_12"): 38.7,
    (6, "no_treatment"): 31.7,   (6, "bun_18_24"): 36.0,
    (6, "bun_13_17"): 37.4,      (6, "bun_12"): 39.6,
    (12, "no_treatment"): 30.6,  (12, "bun_18_24"): 37.0,
    (12, "bun_13_17"): 39.4,     (12, "bun_12"): 42.6,
    (18, "no_treatment"): 29.5,  (18, "bun_18_24"): 37.6,
    (18, "bun_13_17"): 40.7,     (18, "bun_12"): 44.5,
    (24, "no_treatment"): 28.4,  (24, "bun_18_24"): 37.9,
    (24, "bun_13_17"): 41.4,     (24, "bun_12"): 45.7,
    (36, "no_treatment"): 26.3,  (36, "bun_18_24"): 36.4,
    (36, "bun_13_17"): 40.4,     (36, "bun_12"): 45.2,
    (48, "no_treatment"): 24.1,  (48, "bun_18_24"): 34.9,
    (48, "bun_13_17"): 39.4,     (48, "bun_12"): 44.7,
    (60, "no_treatment"): 22.0,  (60, "bun_18_24"): 33.4,
    (60, "bun_13_17"): 38.4,     (60, "bun_12"): 44.2,
    (72, "no_treatment"): 19.8,  (72, "bun_18_24"): 31.9,
    (72, "bun_13_17"): 37.4,     (72, "bun_12"): 43.7,
    (84, "no_treatment"): 17.7,  (84, "bun_18_24"): 30.4,
    (84, "bun_13_17"): 36.4,     (84, "bun_12"): 43.2,
    (96, "no_treatment"): 15.5,  (96, "bun_18_24"): 28.9,
    (96, "bun_13_17"): 35.4,     (96, "bun_12"): 42.7,
    (108, "no_treatment"): 13.4, (108, "bun_18_24"): 27.4,
    (108, "bun_13_17"): 34.4,    (108, "bun_12"): 42.2,
    (120, "no_treatment"): 11.2, (120, "bun_18_24"): 25.9,
    (120, "bun_13_17"): 33.4,    (120, "bun_12"): 41.7,
}

# Known discrepancy note for Q1 escalation:
# At t=120, "no_treatment": spec=11.2, engine produces ~8.7 (delta=-2.5).
# Engine adds BUN modifier of +0.225 mL/min/yr to decline rate,
# increasing annual decline from -2.2 to -2.425 mL/min/yr.
# This compounds over 10 years to ~2.5 eGFR deficit.
# Q1 open: which formula set generated these vectors?
GOLDEN_VECTOR_1_NO_TX_DISCREPANCY = {
    "description": "Q1 discrepancy — no_treatment t=120 spec=11.2, engine=8.7, delta=-2.5",
    "likely_cause": "Engine BUN modifier adds 0.225/yr to decline vs spec which may not apply BUN modifier",
    "reference": "finalized-formulas.md Section 8 Q1",
}

# Treatment path discrepancy (all time points beyond t=1):
GOLDEN_VECTOR_1_TX_DISCREPANCY = {
    "description": "Q1 discrepancy — treatment paths diverge by 1-5 eGFR pts from t=1 onward",
    "likely_cause": (
        "Engine Phase 1 completes at month 3 (saturation curve) with Phase 2 also "
        "starting at month 3. Spec vectors appear to use Phase 1 ending month 3 but "
        "Phase 2 starting month 6. Engine's Phase 1 gain for bun_18_24: "
        "min(6, (35-21)*0.31)=4.34, then Phase 2 adds 4.0 starting month 3. "
        "Spec shows bun_18_24 reaching only ~36.0 at t=6 vs engine's ~39.1."
    ),
    "reference": "finalized-formulas.md Section 8 Q1",
}

# ---------------------------------------------------------------------------
# Vector 2 — Stage 5 High-BUN (BUN 53, eGFR 10, Age 65)
# Source: finalized-formulas.md Section 7, calc spec Section 4
# Note: No creatinine in dispatch spec; we use creatinine=5.0 as placeholder
#       since egfr_override=10.0 bypasses the CKD-EPI calculation.
# ---------------------------------------------------------------------------

GOLDEN_VECTOR_2_INPUT = {
    "bun": 53,
    "creatinine": 5.0,   # placeholder — egfr_override bypasses CKD-EPI
    "age": 65,
    "egfr_override": 10.0,
}

GOLDEN_VECTOR_2_EXPECTED = {
    (0, "no_treatment"): 10.0, (0, "bun_18_24"): 10.0,
    (0, "bun_13_17"): 10.0,    (0, "bun_12"): 10.0,
    (3, "no_treatment"): 8.5,  (3, "bun_18_24"): 14.0,
    (3, "bun_13_17"): 16.4,    (3, "bun_12"): 19.4,
    (12, "no_treatment"): 5.5, (12, "bun_18_24"): 16.1,
    (12, "bun_13_17"): 20.2,   (12, "bun_12"): 24.9,
    (24, "no_treatment"): 2.0, (24, "bun_18_24"): 17.5,
    (24, "bun_13_17"): 22.4,   (24, "bun_12"): 27.4,
    # no_treatment hits 0 by ~month 27 — no spec values at t=36+
    (36, "bun_18_24"): 16.0,   (36, "bun_13_17"): 21.4,
    (36, "bun_12"): 26.9,
    (120, "bun_18_24"): 7.5,   (120, "bun_13_17"): 15.4,
    (120, "bun_12"): 22.4,
}

# ---------------------------------------------------------------------------
# Vector 3 — Mild CKD (BUN 22, eGFR 48, Age 52)
# Source: finalized-formulas.md Section 7, calc spec Section 4
# ---------------------------------------------------------------------------

GOLDEN_VECTOR_3_INPUT = {
    "bun": 22,
    "creatinine": 1.5,   # placeholder — egfr_override bypasses CKD-EPI
    "age": 52,
    "egfr_override": 48.0,
}

GOLDEN_VECTOR_3_EXPECTED = {
    (0, "no_treatment"): 48.0,    (0, "bun_18_24"): 48.0,
    (0, "bun_13_17"): 48.0,       (0, "bun_12"): 48.0,
    (3, "no_treatment"): 47.6,    (3, "bun_18_24"): 48.3,
    (3, "bun_13_17"): 49.3,       (3, "bun_12"): 51.1,
    (24, "no_treatment"): 44.8,   (24, "bun_18_24"): 49.0,
    (24, "bun_13_17"): 52.2,      (24, "bun_12"): 57.4,
    (120, "no_treatment"): 29.2,  (120, "bun_18_24"): 34.0,
    (120, "bun_13_17"): 42.2,     (120, "bun_12"): 52.9,
}

# ---------------------------------------------------------------------------
# Tolerance
# ---------------------------------------------------------------------------

# Per calc spec Section 4: all values must match within ±0.2 eGFR.
# This tolerance applies to spec-vs-engine comparison when the same formula
# is used. Given Q1 discrepancy, treatment path tests are marked xfail until
# Lee confirms which formula the vectors are based on.
GOLDEN_TOLERANCE = 0.2
